kdc_host=kdc.kwaidoo.com

scheduletask.pool.size=50

jetty.resource.servlet.class=cmn.servlet.CommonServlet

web.access.whitelist=

jetty.https.enable=false
jetty.https.port=8443
jetty.https.keystore.path=./conf/ssl/ssl.server.p12
jetty.https.keystore.password=changeit
jetty.https.key.password=changeit
jetty.https.truststore.path=
jetty.https.truststore.password=
jetty.https.protocols=
jetty.https.cipher.suites=

com.bap.nio.wss.enable=false
com.bap.nio.wss.file.crt=conf/ssl/ssl.server.crt
com.bap.nio.wss.file.key=conf/ssl/ssl.server_pkcs8.key

agent.redirect.output.rollingMode=Daily
